llamastack/llama-stack-k8s-operator

.github/workflows/build-image.yml

This commit removes build and push of PR images. It only pushes the image once the code is approved and merged

Update build-image workflow

---

.github/workflows/build-image.yml
Dockerfile
README.md
go.mod

This version updagrade is a follow-up to the operator-sdk update where latest versions require  Go 1.23

Update go version to 1.23

---

Makefile

This PR enhances the Makefile by adding version checking for the controller-gen tool. Previously, the Makefile only checked if controller-gen was installed, but didn't verify if the installed version matched the version specified in `CONTROLLER_TOOLS_VERSION`. This could lead to subtle build issues if the wrong version was being used.
Motivation for this PR was that I had strange recommit issues because I had a local `codegen` binary in `bin` that was 0.17.2, but Makefile references 0.17.3. It didn't get reinstalled, but the GitHub action always installs it afresh (0.17.3) and therefor some differences in the generated manifest were detected.
- Modified the controller-gen target in the Makefile to check both for existence AND version match
- If either the tool doesn't exist or the version …

feat: Add version checking for controller-gen tool

---

.github/workflows/run-e2e-test.yml
Makefile
README.md
controllers/llamastackdistribution_controller.go
go.mod
hack/deploy-ollama.sh
tests/e2e/creation_test.go
tests/e2e/deletion_test.go
tests/e2e/e2e_test.go
tests/e2e/setup_test.go
tests/e2e/test_options.go
tests/e2e/test_utils.go
tests/e2e/validation_test.go

This PR introduces e2e testing package for controller
1. `make deploy e2e-tests`
2. Expected test results:
```
=== RUN   TestE2E
=== RUN   TestE2E/validation
=== RUN   TestE2E/validation/should_validate_CRDs
=== RUN   TestE2E/validation/should_validate_operator_deployment
=== RUN   TestE2E/validation/should_validate_operator_pods
=== RUN   TestE2E/validation/should_validate_prerequisites
=== RUN   TestE2E/creation
=== RUN   TestE2E/creation/should_create_LlamaStackDistribution
=== RUN   TestE2E/creation/should_handle_direct_deployment_updates
=== RUN   TestE2E/creation/should_update_deployment_through_CR
=== RUN   TestE2E/creation/should_check_health_status
=== RUN   TestE2E/deletion
=== RUN   TestE2E/deletion/should_delete_LlamaStackDistribution_CR_and_cleanup_resources
--- PASS: TestE2E …
```

Add e2e tests for the controller

---

Makefile

Kustomize to use direct binary download. With latest changes that updates Makefile to use go-install doesn't seem to be working for kustomize. It downloads the binary successfully, but none of the kustomize commands are able to complete execution. Updated to support cross-platform compatibility
- Add platform-specific environment variables (GOOS, GOARCH) using go env
- Enable Go modules with GO111MODULE=on
- Build static binaries with CGO_ENABLED=0

Fix: Kustomize binary installation

---

.github/mergify.yml

This enables the Mergify bot to:
* automatically merge PRs under certain conditions using the squash method (like we do today)
* ping autors and label PR when the code has conflicts, making it easy to identify by maintainers too

ci: introduce mergify bot

---

.pre-commit-config.yaml
README.md
config/samples/_v1alpha1_llamastackdistribution.yaml
release/operator.yaml

Updated pre-commit hook to update Installer script on manifest generation

chore: Ensure installer script is updated with manifests

---

Makefile

The previous check wasn't entirely correct, since somone can run macOS but use gnu binaries.
Let's remove all ending trailing lines, if any, it doesn't hurt :)

fix: remove trailing line

---

controllers/resource_helper.go

Image pull-policy defaults to `Always` only for :latest tag. Ensure the image is pulled from registry for every updated

chore: Update image pull-policy to Always

---

controllers/llamastackdistribution_controller.go
go.mod

Add diff output when LlamaStackDistribution CR spec changes using go-cmp. The diff is printed separately from structured logging for better readability. This helps operators track and understand changes to CR configurations.
Example:
```
2025-06-16T08:45:56Z    INFO    LlamaStackDistribution CR spec changed  {"namespace": "llama-stack-test", "name": "llamastackdistribution-sample"}
v1alpha1.LlamaStackDistributionSpec{
Replicas: 2,
Server: v1alpha1.ServerSpec{
Distribution: {Name: "ollama"},
ContainerSpec: v1alpha1.ContainerSpec{
Name:      "llama-stack",
Port:      0,
Resources: {},
Env: []v1.EnvVar{
{
Name:      "GOO",
-                                       Value:     "FOOOs",
+                                       Value:     "FOOO",
ValueFrom: nil,
},
{Name: "INFERENCE_MODEL", Value: …
```

feat(controller): add CR spec diff output on updates

---

controllers/llamastackdistribution_controller.go

The first entry in the reconcile loop already initializes a logger with the name and namespace values so there is no need to re-add those.

fix: avoid repeating name and namespace log values

---

controllers/resource_helper.go
controllers/resource_helper_test.go

Depending on the distribution configuration, some models might get downloaded. This is true when the sentence-transformers provider is used. The library will download embedding models in the local filesystem using the HuggingFace library. We want to use the PVC mount to store the Datasets and the Hub artifact. For this, we need to set the `HF_HOME` env variable to our PVC mount.
This is important so that we:
* Avoid re-downloading models if the Pod moves
* Do not fill the host filesystem
* Take advantage of potentially faster storage than the host
In Kubernetes, when we append environment variables, if there's a duplicate name, the last one in the list takes precedence. So, a user-provided environment variable will always be honored.

fix: point HuggingFace home directory to PVC mount

---

pkg/deploy/plugins/name_prefix.go
pkg/deploy/plugins/name_prefix_test.go

feat(name_prefix): add kustomize plugin to prefix resource names

---

.github/workflows/build-image.yml
Dockerfile
Makefile
README.md
docs/create-operator.md

- use local.mk with pre-set env varibles: "make image IMG=XXX" and simplify to "make image"
- introduce new variable "IMG_TAG" to be keep old behavior
- rename target from "docker-build"/"docker-push" to "image-build"/"image-push" since we support podman by default
- create new target "clean"
- update documents and other place referred to updates
test:
1. made local.mk with 
```
VERSION=25.7.2
IMAGE_TAG_BASE=quay.io/wenzhou/llama-stack-k8s-operator
IMG_TAG=$(VERSION)
```
then ran `make image build-installer`
generated `quay.io/wenzhou/llama-stack-k8s-operator:25.7.2`
2. removed local.mk to run `make image build-installer`
it calls `podman build -t quay.io/llamastack/llama-stack-k8s-operator:latest .`

feat: add support in Makefile for better local deveopment

---

api/v1alpha1/llamastackdistribution_types.go
config/crd/bases/llamastack.io_llamastackdistributions.yaml
release/operator.yaml

Since `llamastackdistribution` is quiet a long resource name, I am proposing to use a `shortName` for it.

chore: short name for operator CRD

---

CONTRIBUTING.md
Makefile

The make test extension adds `TEST_PKGS` and `TEST_FLAGS` variables to the Makefile, allowing developers to run specific test packages or functions instead of the entire test suite. This maintains backward compatibility while enabling faster TDD workflows like `make test TEST_PKGS=./pkg/deploy TEST_FLAGS="-v -run TestRenderManifest"`.

feat(cli): enable selective test execution in make test

---

config/rbac/role.yaml
controllers/kubebuilder_rbac.go
controllers/llamastackdistribution_controller.go
release/operator.yaml

Trimming down existing wildcard RBAC permissions via kubebuilder markers.
Tested on an OpenShift 4.18.17 | Kubernetes v1.31.9 cluster.
Closes #18

refactor: consolidate security annotations

---

Makefile
api/v1alpha1/llamastackdistribution_types.go
config/crd/bases/llamastack.io_llamastackdistributions.yaml
config/manager/manager.yaml
controllers/llamastackdistribution_controller.go
docs/api-overview.md
release/operator.yaml

This commit introduces changes to set LLS version using  endpoint `/v1/version`
Resolves #86 
Resultant Status -

Use LLS version endpoint in Status

---

config/manager/manager.yaml
release/operator.yaml

- Update memory resource limit to avoid OOMKilled error 
- As we are watching all configmaps in cluster, we hit this error for larger clusters . We can reconfigure the values once we add optimization for ConfigMap watch.
- Update imagePullPolicy to always, for easier testing

(chore) Update manager deployment spec

---

pkg/deploy/kustomizer.go
pkg/deploy/plugins/field_mutator.go
pkg/deploy/plugins/field_mutator_test.go

Replaces custom dot notation parser with [RFC 6901 JSON Pointer](https://datatracker.ietf.org/doc/html/rfc6901) syntax to handle Kubernetes label keys containing dots (e.g., `app.kubernetes.io/instance`). 
Migration enables proper Service selector transformations where previous dot notation failed on keys like `spec.selector["app.kubernetes.io/instance"]`, unblocking dynamic Service-to-Deployment label matching.

refactor(field_mutator): migrate dot notation to JSON Pointer syntax

---

pkg/compare/comparison.go
pkg/compare/comparison_test.go

Introduces a new `pkg/compare` package that provides utilities for detecting unexpected changes in Kubernetes Service resources by comparing desired vs current states and enforcing resource kind immutability by preventing users from mutating fields that should not be changed on existing resources. The package intelligently ignores operator-managed fields (ports, selectors) and cluster-managed metadata to focus only on detecting external mutations that could impact service functionality.

feat(kustomizer): add service comparison and immutability enforcement utilities

---

CONTRIBUTING.md
controllers/llamastackdistribution_controller_test.go
controllers/suite_test.go
controllers/testing_support_test.go

Refactor controller tests to use `controllers_test` package with shared envtest environment. This consolidates test environment setup in `suite_test.go` using `TestMain` and adds anti-fragile testing patterns including a DistributionBuilder, consolidated test constants, and behavioral helpers. This pull request also documents the intent behind these changes in `CONTRIBUTING.md`.
This is intended to facilitate an upcoming pull request to add a `TestReconcile()` to the controller's test suite to more fully cover the controller's happy path to reconciliation.

refactor(controller): add anti-fragile test patterns and clean up utilities

---

controllers/llamastackdistribution_controller.go
controllers/manifests/base/kustomization.yaml
controllers/manifests/base/service.yaml
pkg/deploy/deploy.go
pkg/deploy/kustomizer.go
pkg/deploy/kustomizer_test.go

Migrate service creation from programmatic to manifest-based Kustomizer pipeline, with added service comparison utilities to detect unexpected changes and enforce field mutability boundaries between operator-managed and cluster-managed state.

feat(controller): migrate service reconciliation to kustomize manifest

---

config/rbac/kustomization.yaml
config/rbac/llsd_editor_role.yaml
config/rbac/llsd_viewer_role.yaml
release/operator.yaml

Adds a reference to the config/rbac/llsd_editor_role.yaml and config/rbac/llsd_viewer_role.yaml files to config/rbac/kustomization.yaml so the ClusterRoles get created upon installation.
Fixes: RHAIENG-496

fix: updating CRD names; including llds editor/viewer roles

---

.github/workflows/build-vllm-cpu-image.yml

Without `cd`, GitHub Actions tries to look for `Dockerfile.cpu` in the local repository instead of the cloned `vllm` repository, where it's actually located.

fix: Change to 'vllm' dir to build vLLM CPU image

---

.github/workflows/build-vllm-cpu-image.yml

We still want to push alpha, beta, and rc images to our quay.io repo, but we don't necessarily want to overwrite the `latest` tag with an alpha, beta, or rc version.
Also schedule this job for once a week, on Fridays, at 12am UTC.

feat: Refuse to overwrite `latest` vllm-cpu image on alpha, beta, or rc tag.

---

Dockerfile

Updating relevant settings to make the same DfFIPS configurations on some other RHOAI components, for the purpose of passing [check-payload](https://github.com/openshift/check-payload/) scans without errors or false-positives.
- CGO settings updated
- Golang version incremented
- Some context / test changes  made to accommodate the Go version update.
Fixes: RHAIENG-663
If merged before 139, then bumps the UBI of the builder image, and:
Closes: #139

standardize DfFIPS settings

---

controllers/resource_helper.go
controllers/resource_helper_test.go

In llama-stack 0.2.17, with the help of
https://github.com/llamastack/llama-stack/pull/2975 the module name containing the server changed. So we need to adapt the entrypoint in consequence.
When using a ConfigMap to store the server configuration, the operator overrides the container entrypoint. This code has been adapted to use the correct module based on the detected llama-stack version.
Also, we now force the entrypoint to use python3 instead of python.

fix: adapt the container entrypoint based on the llama-stack version

---

controllers/resource_helper.go
controllers/resource_helper_test.go

Problem: The current readiness probe fails during documentation ingestion because the endpoint is blocked by synchronous code. This causes the pod to flap in and out of service, even though the process itself is healthy and simply busy. Ending up with pod restart since the Readiness probe keeps failing.
Solution: Replace the readiness probe with a startup probe. This allows the pod to survive long ingestion periods without being prematurely marked unready by Kubernetes. We disable the Readiness probe for now but still ensure some basic health functionality for startup.
Tradeoff: Once the startup probe succeeds, Kubernetes will assume the pod remains ready for traffic. This means we lose the ongoing readiness check and a pod that later becomes overloaded or blocked will still receive …

feat: disable readiness probe and add startup probe

---

config/samples/_v1alpha1_llamastackdistribution.yaml
config/samples/example-with-ca-bundle.yaml
config/samples/example-with-configmap.yaml
tests/e2e/creation_test.go
tests/e2e/deletion_test.go
tests/e2e/e2e_test.go
tests/e2e/test_utils.go

test: remove ollama distribution testing, replace with starter
This focuses testing on the actively maintained starter distribution
while removing support for the older ollama image that's no longer updated.
Also intrduces a list of distro images (currently only 1) that can be tested.
---
test: combine creation and deletion into single lifecycle test
Restructure the creation test to run creation followed by deletion in a single
test suite. This enables testing multiple distribution images sequentially
with proper cleanup between runs.
Changes:
- Add TestCreationDeletionSuite that runs creation then deletion
- Replace TestDeletionSuite with runDeletionTests helper function
- Simplify test structure while maintaining all existing functionality

test: remove ollama distribution testing, replace with starter

---

api/v1alpha1/llamastackdistribution_types.go
config/crd/bases/llamastack.io_llamastackdistributions.yaml
controllers/llamastackdistribution_controller.go
controllers/llamastackdistribution_controller_test.go
docs/api-overview.md
release/operator.yaml

The `.status.serviceURL` field in the `LlamaStackDistribution` resource would now have the value i.e.,:
```
http://<service-name>.<namespace>.svc.cluster.local:<port>
```
Note: the pre-commit linter seems to not like the use of `serviceUrl`. It said to use `serviceURL` instead.
I tested the service by:
1. Running my own version of llama-stack-k8s-operator on OpenShift with the changes in this PR: `make deploy IMG=quay.io/rh_ee_czaccari/llama-stack-k8s-operator:servicestatus4`
2. Created a sample LlamaStackDistribution.
3. Then I ran a test pod:
>kubectl run curl-test --image=quay.io/rh_ee_czaccari/curl:test5 --rm -it --restart=Never -n ollama-dist -- curl -k -v http://llamastackdistribution-sample-service.ollama-dist.svc.cluster.local:8321/v1/models

Add Service Endpoint to LlamaStackDistribution .status

---

.github/workflows/generate-release.yml

This commit updates the docker action tag to unblock the release workflow
Existing error - https://github.com/llamastack/llama-stack-k8s-operator/actions/runs/17920005053/job/50952690570

(chore): Update docker action tag
